runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: app.app

- url: /contract
  script: app.app

- url: /contract/.*
  script: app.app

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
